### ISSUE TITLE
Potential feature: sqlOnly

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Strategus#103]
Some people were having sections of the analysis hang on database queries. It is hard to know what query is run and how to debug query performance.  It would be helpful if there was a way to export all the queries that would be run in the process of the study.

**Comment by anthonysena** [comment]
So DatabaseConnector provides a mechanism for this: https://ohdsi.github.io/DatabaseConnector/articles/Querying.html#logging-all-queries. However, my experience is that the full query is not in the output (only the first N characters where N is a value I forget)

**Comment by anthonysena** [comment]
Closing this out since 1) DatabaseConnector provides this functionality and is configurable when running Strategus and 2) any expansion to the capture of SQL would happen in DatabaseConnector.
