### ISSUE TITLE
Strategus module instantiation fails when running Strategus from a project using renv

### ISSUE THREAD

**Issue by egillax** [OHDSI/Strategus#105]
I have a study package that uses renv. When calling `Strategus::ensureAllModulesInstantiated` from that R project it fails with:

```
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rlang’
```
This seems to come from this [line](https://github.com/OHDSI/Strategus/blob/main/R/ModuleEnv.R#L93C1-L93C1) where it's trying to load `dplyr` from the process calling Strategus. When that process is using `renv` it can't find the dependencies of `dplyr` even though they are installed in that `renv` project.

Steps to reproduce:

1. create a new R project "project", call `renv::init()` and `renv::install('dplyr')`. Then call
```R
libPath <- file.path(find.package('dplyr'), "../")
```
And save/copy `libPath`. 

2. create another R project "module", call "renv::init()" there. Then try to load dplyr there using:
```R
library(dplyr, lib.loc=libPath)
```

**Comment by anthonysena** [comment]
Hi @egillax - I think this is currently a limitation of Strategus whereby it assumes it is being called from the base R environment (i.e. not running in renv). The code you've identified is causing other headaches with Strategus and in speaking with @azimov we had some ideas around how to run this in a different way so we don't require loading this directly from the base R environment. Additionally, I think these changes would allow for it to work when running inside of an renv process directly.

Is it possible to remove the renv part from your project and allow Strategus to handle the setup of the renv environment instead?

**Comment by egillax** [comment]
Hi @anthonysena , Yes I've already removed the renv part from my project as a workaround. But good to know you and @azimov have a possible solution for the future.
