### ISSUE TITLE
Is it possible to make use of targets inside a module

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Strategus#11]
Would it be possible to make use of targets inside a Strategus module? In other words, if a module creates a targets pipeline it wants to run can this pipeline be passed through to the `tar_make` call [here](https://github.com/OHDSI/Strategus/blob/8e840705f045558242e0ec3a1a0d79ca54321732/R/Execution.R#L69) or would the module call `tar_make` inside the module?

**Comment by anthonysena** [comment]
Hey @ablack3 - I think this would be _technically_ possible but why would you want to invoke targets from within the module itself?

**Comment by ablack3** [comment]
Maybe this a bad idea but I could see value in using targets within a module. A module might need to execute multiple steps with dependencies between those and we might not need to rerun all of those steps every time we make a change to the input json.

**Comment by anthonysena** [comment]
Sorry - I did not mean to imply that it was a bad idea. I just hadn't thought about doing what you described; I think it is technically possible and might have the advantages as you described. I know that you are working on the OhdsiTargets and if I remember your demo right, you were able to break operations (cohort generation?) into smaller blocks to avoid re-doing cohort generations?

**Comment by ablack3** [comment]
No worries. Yea we are exploring this with ohdsitargets. I was thinking since Strategus is still in early development we could consider making it possible for a module to somehow pass a list of targets into the targets pipleline that Strategus executes. This would open the possibility of making use of target factories in Strategus.

**Comment by anthonysena** [comment]
I think we can explore this possibility. Strategus is defining the top-level targets workflow based on the overall analysisSpecification. Each module is then handed its own part of the specification (and the shared part) and it is running inside of an renv session. Presumably we could invoke targets since the module is running in its own session but I'd have to try to be sure. I'd just want to watch for circular reference problems here.

**Comment by anthonysena** [comment]
@ablack3 - I know this has been out here a bit but did you still want to explore this option with Strategus and OhdsiTargets?

**Comment by ablack3** [comment]
I think we should develop these ideas separately for now. If we think about overall "OHDSI System" design as layers of abstraction I have a preference for a layer that executes any R code (or even python code) in a standardized environment (OS type, Java, system dependencies, R package cellar, etc). This will allow a lot of flexibility. I think the generation of R code to run and the actual execution should be separated.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/10227522/184234426-32570aea-8ccb-45eb-b720-2218e7c0560b.png">

**Comment by anthonysena** [comment]
I'm curious: in this abstraction, I would imagine that OhdsiTargets will be used in the `JSON -> R code` abstraction layer?

**Comment by ablack3** [comment]
I suppose it could. Right now we are thinking of an analysis as an R project. ohdsitargets provides target factory functions that can be used in a targets pipeline. Its goal is to provide shortcuts to creating a large number of "targets" in exactly the same way that [stantargets](https://docs.ropensci.org/stantargets/) works for stan.  We'll implement some good examples before symposium and then get some feedback. To use it in this system (for the time being) we would go directly to the R execution endpoint skipping the UI and json layer completely. 

What is important is that we all have a layer/interface that we can "plug" into. An R execution endpoint is very general and lets anyone plug into it. I don't even think it should be restricted to R but probably include python or SQL. 

Strategus seems to combine code generation and exectution together. Currently those are separated in Atlas/WebApi. JSON to R is handled by Hydra and execution is handled by [executionengine](https://github.com/OHDSI/WebAPI/tree/master/src/main/java/org/ohdsi/webapi/executionengine).
