### ISSUE TITLE
Error seen running Characterization

### ISSUE THREAD

**Issue by greshje** [OHDSI/Strategus#124]
I'm seeing the following error running characterization:

```
Error executing SQL:
java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: Table or view not found: demo_temp.iajrqtiaagg_cohorts; line 1 pos 94
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$execute$1(SparkExecuteStatementOperation.scala:498)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:124)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:410)


```

Full output:
[full-output.txt](https://github.com/OHDSI/Strategus/files/14271305/full-output.txt)

errorReport.R File:
[errorReport.R.txt](https://github.com/OHDSI/Strategus/files/14271319/errorReport.R.txt)

errorReportR.txt
[errorReportR.txt](https://github.com/OHDSI/Strategus/files/14271321/errorReportR.txt)

Strategus Versions:
```
> Strategus::getModuleList()
# A tibble: 8 × 7                                                                                                                          
  module                         version remoteRepo remoteUsername moduleType mainPackage              mainPackageTag
  <chr>                          <chr>   <chr>      <chr>          <chr>      <chr>                    <chr>         
1 CharacterizationModule         v0.5.0  github.com OHDSI          cdm        Characterization         v0.1.3        
2 CohortDiagnosticsModule        v0.2.0  github.com OHDSI          cdm        CohortDiagnostics        v3.2.5        
3 CohortGeneratorModule          v0.3.0  github.com OHDSI          cdm        CohortGenerator          v0.8.1        
4 CohortIncidenceModule          v0.4.0  github.com OHDSI          cdm        CohortIncidence          v3.3.0        
5 CohortMethodModule             v0.3.0  github.com OHDSI          cdm        CohortMethod             v5.2.0        
6 PatientLevelPredictionModule   v0.3.0  github.com OHDSI          cdm        PatientLevelPrediction   v6.3.6        
7 SelfControlledCaseSeriesModule v0.4.1  github.com OHDSI          cdm        SelfControlledCaseSeries v5.1.1        
8 EvidenceSynthesisModule        v0.6.0  github.com OHDSI          results    EvidenceSynthesis        v0.5.0        

```

Some additional information from my notes (It looks like this was seen in Characterization v0.1.1 but still exists in v0.1.3 but not in the main branch of Characterization):

> It looks like this was a legit bug in Characterization (probably related to this: https://github.com/OHDSI/Characterization/issues/30, https://github.com/OHDSI/Characterization/pull/31).  
> 
> I was able to reproduce the error by downloading and installing Characterization from source.  Installing from v0.1.1 gives the error when I run a modified version of their example code that points to my data.  Checking out main and re-installing from source resolves the issue when running the test code.  
> 
> Strategus uses v0.1.1 (this is the latest version [at the time, the Strategus version tested here used v0.1.3]).

**Comment by anthonysena** [comment]
Hi @greshje can you upload "C:/temp/ergasia/_MODULES/CharacterizationModule_0.5.0/errorReportSql.txt" so I can see what the SQL error is?

**Comment by anthonysena** [comment]
Closing this out due to inactivity - @greshje if your still facing an issue, please re-open and provide those details and we can track it down.
