### ISSUE TITLE
Upload results error

### ISSUE THREAD

**Issue by Mikhail-iontsev** [OHDSI/Strategus#129]
I'm getting a keyring error while running Strategus on Eunomia using the ExecuteStrategusOnEunomia script provided with the package
<img width="1349" alt="Screenshot 2024-03-27 at 00 50 02" src="https://github.com/OHDSI/Strategus/assets/92372420/0ef2ddd3-51b8-490e-b815-d89dbebdbaa3">

OS: Mac OS Sonoma
Arch: Arm
R version: 4.3.3

**Comment by anthonysena** [comment]
Hi - sorry for the delay here. I'm not sure if you are still facing an issue? Please let me know and we can try to see what may be happening here.

**Comment by anthonysena** [comment]
Closing out due to age
