### ISSUE TITLE
R6 functions documentation missing

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Strategus#183]
Specifically, I was looking at the [documentation for `addEvidenceSynthesisModuleSpecifications()`](https://ohdsi.github.io/Strategus/reference/addEvidenceSynthesisModuleSpecifications.html), which has a link to `EvidenceSynthesisModule$createModuleSpecifications()` that is dead. 

Now there is no reference manual for how to create specifications for the EvidenceSynthesis module.

**Comment by anthonysena** [comment]
Thanks for reporting this - not sure why the link is not working so I will investigate. The documentation for the EvidenceSynthesis module is here: https://ohdsi.github.io/Strategus/reference/EvidenceSynthesisModule.html and links between different methods of the class seem broken but you can navigate around using the right-hand menu that appears.
