### ISSUE TITLE
renv for python 

### ISSUE THREAD

**Issue by jreps** [OHDSI/Strategus#22]
I found this https://rstudio.github.io/renv/articles/python.html - it seems we may be able to also use renv for the python dependencies in PLP.  If I add an environment.yml into the PatientLevelPredictionModule - would it be possible for Strategus to create a conda environment with that configuration?

**Comment by anthonysena** [comment]
Moving this to the v1.0 milestone since we'd like to change the paradigm of restoring the execution environment which should include the Python environment for PLP.

**Comment by anthonysena** [comment]
Closing and tracking via ohdsi-studies/StrategusStudyRepoTemplate#2
