### ISSUE TITLE
Issue with the keyring

### ISSUE THREAD

**Issue by ted9219** [OHDSI/Strategus#24]
Hi all,

I've tried to test the Strategus for cohort generation and developing a prediction model.

**however, the keyring package is aborted when running each module like below.** 

![image](https://user-images.githubusercontent.com/42205861/202384197-c2c448b7-9070-44d4-9a84-0a691bc95f11.png)

**It seemed that the password for using the keyring for the first time in each session was required but it didn't be provided for each module.**

![image](https://user-images.githubusercontent.com/42205861/202383156-9f55cc7a-7235-4849-b2de-54aebf495e8e.png)

**this was my sessioninfo.**

![image](https://user-images.githubusercontent.com/42205861/202384338-55b35a6b-d54a-46d8-b47c-8dc7656287a2.png)

**If you have any idea for this, please let me know.**

**Comment by ted9219** [comment]
When I add a line as below manually into the script in the RunModule.R of Strategus package, I finally succeed to execute each module without the keyring error. Now, we need to how to parameterize or solve this another way without putting our password into the script.
```r 
keyring::unlock('system', password = 'mypassword')
```

**Comment by anthonysena** [comment]
Hi @ted9219 thanks for this information. I've been working on Windows so had not encountered this issue myself but in speaking with a few other people who are running Strategus on a non-Windows environment, they are facing similar challenges here. 

My plan is to extend the functions `storeConnectionDetails` and `retrieveConnectionDetails` to allow for specifying a keyring store as part of the function call. By default this will be NULL and for folks like yourself, you can establish a keyring and then make use of that when storing/retrieving the connection details. 

Let me know if that would work for you. The modification would be here: https://github.com/OHDSI/Strategus/blob/develop/R/Settings.R#L198 and look like this:

```r
keyring::key_set_with_value(connectionDetailsReference, password = connectionDetails, keyring = <your keyring>)
```

**Comment by ted9219** [comment]
Hi @anthonysena, 

I've tried with the develop branch of Strategus, however, I don't resolve the error like this, unfortunately. I think maybe even we can select a specific keyring, the keyring is still locked in a new R session, and therefore module is aborted.

![image](https://user-images.githubusercontent.com/42205861/202858013-f9a32b9e-1136-4b62-9d2b-bc77726c5681.png)

**Comment by anthonysena** [comment]
@ted9219 - The branch `issue-24-keyring` has some updates to try and address this issue you faced with keyring. 

The approach done in #27 allows for you to specify the keyring name & password when calling the various functions in Strategus to store the connection details and to execute the pipeline. The keyring settings are then saved so that each session that is invoked can obtain the keyring info and the necessary connection information. I don't particularly love this approach but for now I wanted to see if this might work for you?

**Comment by ted9219** [comment]
@anthonysena 

Thank you, Anthony. I've checked your fix and it works fine!
A few more experiences to share:
1, If keyring is used for the existing connectionDetails, the keyring that binds keys for each item of the connectionDetails using the storeConnectionDetails funciton. so connectionDetailsReference must be different from the existing keyring name. 

for example, I already have keyring named 'test' which have each keys for the connectionDetails like below. 

```r
connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = keyring::key_get(keyring = 'test', service = 'dbms', username = 'ted9219'),
  server = keyring::key_get(keyring = 'test', service = 'server', username = 'ted9219'),
  user = keyring::key_get(keyring = 'test', service = 'user', username = 'ted9219'),
  password = keyring::key_get(keyring = 'test', service = 'password', username = 'ted9219'),
  port = keyring::key_get(keyring = 'test', service = 'port', username = 'ted9219'),
  pathToDriver = keyring::key_get(keyring = 'test', service = 'pathToDriver', username = 'ted9219')
)
```

then It may overwrite the exsiting keyring ('test') when I use the same name for that keyring. therefore I recommend a different keyring name as the connectionDetailsReference.
```r
connectionDetailsReference = 'AUSOM'
```

2. According to your opinion, the method of directly entering the keyringPassword may need to be changed in the future. 

3. Shouldn't the keyring be added to the renv.lock file of all modules?

If you need any help, please let me know. 
Thank you again.

**Comment by anthonysena** [comment]
Thanks @ted9219 for the review and for the points above! 

> 1, If keyring is used for the existing connectionDetails, the keyring that binds keys for each item of the connectionDetails using the storeConnectionDetails function. so connectionDetailsReference must be different from the existing other key names.

That's correct - I'll note this in the function documentation so it is clear.

> 2. According to your opinion, the method of directly entering the keyringPassword may need to be changed in the future.

Yes, I plan to change my branch to allow the user to specify the keyring password via an environment variable instead of making it part of the function arguments. The desire to use keyring in Strategus was to steer people away from putting potentially secret information into their execution script.

> 3.  Shouldn't the keyring be added to the renv.lock file of all modules?

Keyring is a dependency for Strategus but not the modules as Strategus extracts the info using keyring and passes it to the modules via the `executionSettings`.

**Comment by anthonysena** [comment]
This fix is now on the `develop` branch and will be part of the v0.0.3 release.
