### ISSUE TITLE
Keep a record of time needed to execute each module

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Strategus#4]
This will be part of the output (as a CSV file), and can be shared between sites (unlike a log file, which may not always be shared because it has no well-defined content).

The thinking is that, if a module take a really long time to execute, we can explore the module-specific log file to debug.

**Comment by anthonysena** [comment]
This is now added to the output (and log file) for each execution. If we need to standardize this into the results model we can track that as a separate task.
