### ISSUE TITLE
Simplify module installation

### ISSUE THREAD

**Issue by azimov** [OHDSI/Strategus#45]
Currently, developing modules is fairly painful. My workflow has been to developing on a fork and making bug fixes by creating releases, which is tedious and fraught with potential errors.

The process could be greatly simplified if we added functionality to support installation to and from disk.
I'm imagining an API similar to `remotes::install_github/install`.

In this context a user would download a module release by sampling executing commands like:

```{r}
Strategus::install_github("OHDSI/CohortGenerator") # get latest release
Strategus::install_github("OHDSI/CohortGenerator", ref = "develop") # get development version
Strategus::install_github("OHDSI/CohortGenerator", ref = "v0.1.1") # get specific version
Strategus::install_local("./PLPWithCustomisations") # install from disk
```

These could then save to disk in a location that is either in the project for re-use or within some global space configurable with an environment variable.

The install process could also optionally instantiate the modules.

Form this we could also add functionality such as:

```
Strategus::getAvailableModules() # Returns a list of all the currently installed modules with their version numbers
```

I would also like to see module code somewhat isolated from the R environment so instead of:

```{r}

# bad
source("https:://pathToGithubUrl/ModuleSettings.R")
createModuleSepecifications(...)
```

We could implement a function that returns a locally sourced environment:

```{r}
# better
moduleEnv <- new.env()
source("pathToModuleSettings.R", local = moduleEnv)
< Insert simple module validation functions >
moduleEnv$createModuleSepecifications(...)
```

I also note that this would allow the creation of common interfaces around module settings functions instead of `createCohortGeneratorModuleSpecifications` it would be a common function `createModuleSepecifications`.

**Comment by anthonysena** [comment]
Linking this to #29 since they are related.

**Comment by anthonysena** [comment]
New refactor of module approach should address this so closing it out.
