### ISSUE TITLE
required metadata tables check fails with DatabaseConnector < 6.0

### ISSUE THREAD

**Issue by egillax** [OHDSI/Strategus#61]
In ```DatabaseConnector``` 6.0 the ```getTableNames``` was [changed](https://github.com/OHDSI/DatabaseConnector/blob/25dd311f1466ac3f7e01de39b74016509f6c977e/NEWS.md?plain=1#L42) to output lowercase instead of uppercase. 

The metadata table [check](https://github.com/OHDSI/Strategus/blob/main/R/DatabaseMetaData.R#L47) in Strategus expects the table names in lowercase and so fails always if using ```DatabaseConnector``` < 6.0

In the Strategus ```DESCRIPTION``` file it says ```DatabaseConnector``` >= 5.1 is supported.

Simplest fix is probably to call ```tolower()``` on the output from ```DatacaseConnector::getTableNames``` [here](https://github.com/OHDSI/Strategus/blob/main/R/DatabaseMetaData.R#L41)

**Comment by anthonysena** [comment]
Thanks @egillax - I'll patch that up and let you know when it is ready!
