### ISSUE TITLE
Fail fast when using a dbms that requires temp emulation when tempEmulationSchema is NULL

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Strategus#73]
If the user's data is in Oracle or Bigquery I suggest that Strategus throw an error if tempEmulationSchema is not set. The error should be thrown during the initial argument checks [here](https://github.com/OHDSI/Strategus/blob/d50b9b7a4822278a62de01b16d3b768d398de1d3/R/Execution.R#L55) before doing any work (i.e. fail fast).

**Comment by anthonysena** [comment]
Thanks @ablack3 - fully agree. I also need to expose some option for setting the `tempEmulationSchema` in the execution settings as it appears that setting the option globally is not honored when executing inside of a module.

**Comment by anthonysena** [comment]
I've conflated two issues - it appears the modules will make use of the global options. The issue w/ the `tempEmulationSchema` has been logged here: https://github.com/OHDSI/CohortGenerator/issues/99. I'll add the check as you suggested.
