### ISSUE TITLE
Release studies with dependencies installed for launch shinyApp locally

### ISSUE THREAD

**Issue by msuchard** [OHDSI/Strategus#78]
@anthonysena , @pbr6cornell  -- is there an easy / convenient way to distribute `Strategus`-based studies so that data partners can quickly / easily launch a local `shinyApp` to view their own results?

**Comment by anthonysena** [comment]
Tagging @jreps - we don't currently have a script to launch the results viewer for the SOS studies. Could we add that to the study repos? Then we should think about @msuchard's item here so that perhaps we can launch the results viewer via Strategus? Open to suggestions here.

**Comment by haydenbspence** [comment]
@anthonysena I have found Strategus to work well on Broadsea, and I could see adjustments to their docker-compose implementing this. Of course, that is for sites that can run Docker (many are not able to without some involved IT approvals).

**Comment by anthonysena** [comment]
Could be done using docker and linking to #97

**Comment by azimov** [comment]
@anthonysena shiny app containers will hopefully be supported with the next releases of the ShinyAppBuilder/OhdsiShinyModules [here](https://github.com/OHDSI/ShinyAppBuilder/pull/24).

**Comment by anthonysena** [comment]
Closing and tracking via ohdsi-studies/StrategusStudyRepoTemplate#3
