### ISSUE TITLE
Remove local library package dependencies

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Strategus#96]
When Strategus runs a module, it dynamically creates an R script to run the module and as part of that script it will attach packages from the user's base R library. Here is an example of the head of the `StrategusScript.R`:

```r
library(R6, lib.loc = 'D:/R/R-4.2.3/library/R6/..')
library(dplyr, lib.loc = 'D:/R/R-4.2.3/library/dplyr/..')
library(openssl, lib.loc = 'D:/R/R-4.2.3/library/openssl/..')
library(keyring, lib.loc = 'D:/R/R-4.2.3/library/keyring/..')
library(DatabaseConnector, lib.loc = 'D:/R/R-4.2.3/library/DatabaseConnector/..')
library(CohortGenerator, lib.loc = 'D:/R/R-4.2.3/library/CohortGenerator/..')
library(ParallelLogger, lib.loc = 'D:/R/R-4.2.3/library/ParallelLogger/..')
library(Strategus, lib.loc = 'D:/R/R-4.2.3/library/Strategus/..')
source("Main.R")
```

Since the script is attempting to use functions of Strategus in this script, we need to attach Strategus and its dependencies. This is problematic when running the CohortGeneratorModule since instead of using the version of CohortGenerator in the renv.lock file, it uses the one from the base R library. 

We should remove the CohortGenerator dependency as a first step. A secondary step might be to revise this script to limit the amount of base libraries that are required when running the Strategus script.

**Comment by anthonysena** [comment]
Discussion with @azimov on this topic: we may be able to use an R `environment` to isolate the loading/unloading of these dependencies instead of using the base R `library` commands.

**Comment by azimov** [comment]
I'm not 100% sure what we discussed here but from memory you want to use something like the following:


```{r}
# inside Main.R
library(CohortGenerator, lib.loc = 'D:/R/R-4.2.3/library/CohortGenerator/..')
loadCgCohorts <- funtion(...) {
    CohortGenerator::someInternalFunction(...)
}
```

Then call 
```{r}
mainEnv <- new.env()
source("Main.R", local = mainEnv)

mainEnv$loadCgCohorts(...)
```


I'm pretty sure this would source the package inside the environment and avoid polluting the global namespace.

**Comment by anthonysena** [comment]
A few notes after digging into this problem in more detail. Part of the reason why we are loading specific R libraries in this script is to allow for using functions of Strategus when running a module via the `renv::run()` command. Specifically this part of running the module:

https://github.com/OHDSI/Strategus/blob/00d0c0025e252c8cf2c0aaaffdda31057f93bb67/R/RunModule.R#L99-L111

I've been able to modify this (on a local branch) to define the `retrieveConnectionDetails` function using the definition inside of the Strategus package so that we can avoid having to depend on Strategus when calling `renv::run()` which allows us to remove the need to attach the libraries listed earlier in this thread. The root of using the `library()` approach stems from problems restoring modules as described in #75. Once that issue is resolved, I think we can avoid attaching any packages from the local R library. 

Now for the other issue: the scripts generated by Strategus assume that the underlying module has specific dependencies in the renv.lock file. At the moment these are: keyring, ParallelLogger, DatabaseConnector and checkmate (and their respective dependencies). I'm going to link this to #69 so that we have some mechanism in place to ensure a module meets some minimum standards so that we can ensure proper use in Strategus pipelines.
